
#defaultName: ${DW_DEFAULT_NAME:-User}

# Server settings
server:

  type: simple
  connector:
      type: http
      port: 8080
  rootPath: '/api/*'
  applicationContextPath: /

# Database settings
database:

  driverClass: org.postgresql.Driver
  user: admin_nf
  password: admin123
  url: jdbc:postgresql://localhost/prod_db

  properties:
    charSet: UTF-8

  # time to wait on empty pool before throwing exception
  maxWaitForConnection: 1s
  # the min & max number of connections to keep open
  minSize: 8
  maxSize: 32
  # validate idle connections
  checkConnectionWhileIdle: true

# Logging settings
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  loggers:
    com.austinpetrie.notefinder: DEBUG
    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG

# Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
# Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
# Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

# the key needs to match the suffix of the renderer
#viewRendererConfiguration:
#    .ftl:
#        strict_syntax: yes
#        whitespace_stripping: yes

metrics:
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      prefix: notefinder
      frequency: 1m
